
## 7. Lists

### Explanation

Lists are ordered collections of items. They can hold any type of data and are mutable.

Useful functions and methods:

- `append(item)`: adds item to the end
- `remove(item)`: removes the first occurrence of item
- `len(list)`: returns number of elements
- `sort()`: sorts the list in place
- `sum(list)`: returns the sum of all numeric elements
- `max(list)`: returns the largest item

### Examples

Looping through a list of fruits and printing them.


In [ ]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

Adding and removing items from a list.


In [ ]:
foods = ["pizza", "sushi"]
foods.append("tacos")
foods.remove("pizza")
print(foods)  # Output: ['sushi', 'tacos']


Sorting a list of numbers.


In [ ]:
numbers = [5, 1, 4, 3, 2]
numbers.sort()
print(numbers)  # Output: [1, 2, 3, 4, 5]


### Exercises

1. Create a list of 5 of your favorite foods and print it.

In [ ]:
favourite_foods = ["pizza", "sushi", "tacos", "ice cream", "pasta"]

2. Add a new food to your list and print the updated list.

In [ ]:
favourite_foods.append('burger')

3. Remove an item from your list.

In [2]:
favourite_foods = ["pizza", "sushi", "tacos", "ice cream", "pasta"]
favourite_foods.remove('burger')

ValueError: list.remove(x): x not in list

4. Sort the list alphabetically and print it.

In [7]:
favourite_foods = ["pizza", "sushi", "tacos", "ice cream", "pasta"]
favourite_foods.sort()
print(favourite_foods)

['ice cream', 'pasta', 'pizza', 'sushi', 'tacos']


5. Write a function that takes a list and prints only items with more than 5 letters.

In [8]:
favourite_foods = ["pizza", "sushi", "tacos", "ice cream", "pasta"]
for word in favourite_foods:
    if len(word) > 5:
        print(word)

ice cream



---

## 8. Arrays

### Explanation

Arrays are like lists but are more efficient for numerical computations. In Python, you typically use NumPy arrays.

Useful NumPy functions:

- `np.array([...])`: creates an array
- `np.mean(array)`: average of elements
- `np.max(array)`: maximum value
- `np.min(array)`: minimum value
- `np.sum(array)`: sum of all elements

### Examples

Creating an array and finding its mean.


In [ ]:
import numpy as np
nums = np.array([10, 20, 30])
print(np.mean(nums))


Multiplying all elements of an array.


In [ ]:
arr = np.array([1, 2, 3])
print(arr * 2)


Creating a 2D array.


In [18]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]



### Exercises

1. Create a NumPy array with numbers from 1 to 10.

In [ ]:
test_array = np.array([1,2,3,4,5,6,7,8,9,10])

2. Multiply every element in the array by 2 and print it.

In [11]:
import numpy as np
test_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(test_array * 2)

[ 2  4  6  8 10 12 14 16 18 20]


3. Find the mean and maximum of the array.

In [12]:
import numpy as np
print(test_array.mean())
print(test_array.max())# Your answer goes here

5.5
10


4. Create a 2D array (matrix) and print it.

In [17]:
import numpy as np
matrix = np.array([[2,3],[3,4]])
print(matrix)

[[2 3]
 [3 4]]


5. Write a function that receives a NumPy array and returns how many elements are greater than 50.

In [27]:
import numpy as np
array = np.array([3,2,10,42,521,32,51235,1235,234])
def greater_than_50(call):
    new = call[call>50]
    return new

store = greater_than_50(array)
print(store)


[  521 51235  1235   234]



---

## 9. Dictionaries

### Explanation

Dictionaries store data in key-value pairs. Keys must be unique.

Useful functions and methods:

- `dict.keys()`: returns a list of keys
- `dict.values()`: returns a list of values
- `dict.items()`: returns a list of key-value tuples
- `dict.get(key)`: gets the value for a key safely

### Examples

Looping through a dictionary and printing each subject and its score.


In [28]:
scores = {"math": 90, "english": 85, "science": 95}
for subject, score in scores.items():
    print(subject, score)

math 90
english 85
science 95



Accessing values and checking keys.


In [29]:
person = {"name": "Alice", "age": 17}
print(person["name"])
print(person.get("city", "Not specified"))

Alice
Not specified



Printing all keys and values.


In [41]:
for key in person.keys():
    print(key)
for value in person.values():
    print(value)

name
age
Alice
17



### Exercises

1. Create a dictionary to store the name and age of a person.

In [ ]:
visual = {
    'alice': 12,
    'aev': 13,
    'new': 120,

}

2. Add a new key-value pair (e.g., city) to your dictionary.

In [34]:
visual = {
    'alice': 12,
    'aev': 13,
    'new': 120,

}
visual['joe'] = 13
print(visual)

{'alice': 12, 'aev': 13, 'new': 120, 'joe': 13}


3. Update the age of the person.

In [35]:
visual = {
    'alice': 12,
    'aev': 13,
    'new': 120,

}
visual['alice'] = 14
print(visual)

{'alice': 14, 'aev': 13, 'new': 120}


4. Print all keys and values.

In [40]:
visual = {
    'alice': 12,
    'aev': 13,
    'new': 120,

}
print(visual.values())
print(visual.keys())

dict_values([12, 13, 120])
dict_keys(['alice', 'aev', 'new'])


5. Write a function that takes a dictionary of subject scores and returns the average score.

In [44]:
scores = {
    'alice': 14,
    'john': 20,
    'albert': 15,

}
import numpy as np
list = np.array([])
for i in scores.values():
    list = np.append(list,i)

list = np.mean(list)
print(list)

16.333333333333332
